# @package _global_
defaults:
  - /encoder: cnn
  - /decoder: dcnn

model:
  _target_: model.AutoEncoder
  _recursive_: False
  # encoder:
  #   _target_: model.CNN
  #   channel_list: ${channel_list}
  # decoder:
  #   _target_: model.DCNN
  #   channel_list: ${channel_list}

channel_list:
  - 64
  - 128
  - 256
  - 512
  - 512
