# @package _global_

scorer:
  _target_: eval.score_autoencoder
  cfg:
    plot: False
    save_x: False
    fig_w: 10
    fig_h: 10
    target_gene:
      - Vxn
      - Ttr
    random_seed: ${random.seed}
